### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by andyss2k** [Hitachi/node-red-contrib-opensky-network#1]
Thank you for this node.

I have two feature requests if you are able to implement:

1. Ability to use an Opensky User ID and Password to be able to fetch in 5 second intervals instead of 10 (https://opensky-network.org/apidoc/rest.html#limitations-for-opensky-users).

2. Output to different ADSB formats such as BaseStation/SBS, Beast/ModeS, etc., if we do not want to use Node Red maps or for use in other apps.

For #2, I have no idea if I have worded it correctly but I was wondering if different output formats can be implemented from the node to feed to such things as tar1090 or modesmixer2.

**Comment by kazuhitoyokoi** [comment]
Thank you for using the OpenSky Network node.

Actually, the Node generator tool which I used in the node development cannot generate Node-RED node with authentication. Therefore, I recommend that you use the inject and http request nodes which Node-RED flow editor has as the default to access the OpenSky Network API with Basic authentication instead of this node.

I'm not familiar with other formats. If there is good use case using the format, I can consider learning it and instructing how to convert the format.
